name       : nextcloud-client
version    : 2.3.2
release    : 1
source     :
    - https://github.com/nextcloud/client_theming/archive/v2.3.2.tar.gz : fbebbcfc538654d7a5373062d2165638a9bd9e5dbe62b5f4552a942b0b931617
    - https://download.owncloud.com/desktop/stable/owncloudclient-2.3.2.tar.xz : a1199d2b957a28081aff11a2a7e471ca09c965bbb1b51b1b7b7a8706304f5f09
license    : GPL-2.0
component  : network.download
libsplit   : no
summary    : Nextcloud themed desktop client
description: |
    Nextcloud client enables you to connect to your private
    Nextcloud Server. With it you can create directories in your home
    directory, and keep the contents of those directories synced with
    the server. Simply copy a file into the directory and the desktop
    synchronisation client does the rest.
#patterns   :
#    - kde-dolphin :
#        - /usr/lib64/libnextclouddolphinpluginhelper.so
#        - /usr/lib64/qt5
#        - /usr/share/kservices5
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    # extra-cmake-modules
    # kcoreaddons-devel
    # kio-devel
    - libiconv-devel
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
setup      : |
    tar xf ${sources}/owncloudclient-${version}.tar.xz
    rm -rf client
    mv owncloudclient-${version} client

    # fix desktop file
    sed -i -e "/^Icon.*=/s/@APPLICATION_EXECUTABLE@/Nextcloud/" client/mirall.desktop.in
    sed -i "s/Utility;X-SuSE-SyncUtility;/Network;/" client/mirall.desktop.in
    sed -e '/^#.*$/d' -e '/^$/d' -i client/mirall.desktop.in

    %cmake client -DOEM_THEME_DIR=$workdir/nextcloudtheme
build      : |
    %make
install    : |
    %make_install

    # remove nemo extensions
    rm -fr $installdir/usr/share/nemo-python
