name       : nextcloud-client
version    : 2.3.3
release    : 2
source     :
    - https://github.com/nextcloud/client_theming/archive/v2.3.3.tar.gz : e3c4393095206648c96980fb23d0520658b3aa8a9a1e31db38b6f59024cb6f8b
    - https://download.owncloud.com/desktop/stable/owncloudclient-2.3.3.tar.xz : aac1bbc16629041795ebb67151abfe109b0c220161e1f7a3f431311e2c6dade4
license    : GPL-2.0
component  : network.download
libsplit   : no
summary    : Nextcloud themed desktop client
description: |
    Nextcloud client enables you to connect to your private
    Nextcloud Server. With it you can create directories in your home
    directory, and keep the contents of those directories synced with
    the server. Simply copy a file into the directory and the desktop
    synchronisation client does the rest.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - libiconv-devel
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
setup      : |
    tar xf ${sources}/owncloudclient-${version}.tar.xz
    rm -rf client
    mv owncloudclient-${version} client

    # fix desktop file
    sed -i -e "/^Icon.*=/s/@APPLICATION_EXECUTABLE@/Nextcloud/" client/mirall.desktop.in
    sed -i "s/Utility;X-SuSE-SyncUtility;/Network;/" client/mirall.desktop.in
    sed -e '/^#.*$/d' -e '/^$/d' -i client/mirall.desktop.in

    %cmake client -DOEM_THEME_DIR=$workdir/nextcloudtheme
build      : |
    %make
install    : |
    %make_install

    # remove nemo extensions
    rm -fr $installdir/usr/share/nemo-python
