name       : nextcloud-client
version    : 2.5.0
release    : 5
source     :
    - https://github.com/nextcloud/desktop/archive/v2.5.0.tar.gz : 4d639f43e49fd4367cd1b99bf21aecb2eac3bd89a7b0d96c7d2a0975baad6528
license    : GPL-2.0-only
component  : network.download
libsplit   : no
summary    : Nextcloud desktop client
description: |
    Nextcloud client enables you to connect to your private
    Nextcloud Server. With it you can create directories in your home
    directory, and keep the contents of those directories synced with
    the server. Simply copy a file into the directory and the desktop
    synchronisation client does the rest.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - libiconv-devel
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
    - qt5-svg
setup      : |
    # No, you don't require 1.1 Nextcloud, don't lie to me.
    sed -i 's:OpenSSL 1.1:OpenSSL 1.0:g' CMakeLists.txt
    %cmake
build      : |
    %make
install    : |
    %make_install

    # remove nemo extensions
    rm -fr $installdir/usr/share/nemo-python
