name       : nextcloud-client
version    : 3.8.2
release    : 41
source     :
    - https://github.com/nextcloud/desktop/archive/refs/tags/v3.8.2.tar.gz : 6186aaa70b82b06b4531cff2e55e0dd38a0d817de7ef039a81293d82cb05e8c0
homepage   : https://docs.nextcloud.com/desktop
license    : GPL-2.0-or-later
component  :
    - network.download
    - dolphin-integration : network.download
libsplit   : no
summary    :
    - Nextcloud client enables you to connect to your private Nextcloud Server. With it you can create directories in your home directory, and keep the contents of those directories synced with the server.
    - dolphin-integration : Dolphin file manager integration for the Nextcloud client.
description:
    - Nextcloud client enables you to connect to your private Nextcloud Server. With it you can create directories in your home directory, and keep the contents of those directories synced with the server.
    - dolphin-integration : Dolphin file manager integration for the Nextcloud client.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebSockets)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(cloudproviders)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - inkscape
    - karchive-devel
    - kio-devel
    - kwindowsystem-devel
    - libiconv-devel
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
    - qt5-graphicaleffects
    - qt5-svg
    - qt5-webengine
    - qt5-webkit
    - dolphin-integration :
        - nextcloud-client
patterns   :
    - dolphin-integration :
        - /usr/lib64/libnextclouddolphinpluginhelper.so
        - /usr/lib64/qt5/plugins/kf5/overlayicon/nextclouddolphinoverlayplugin.so
        - /usr/lib64/qt5/plugins/kf5/kfileitemaction/nextclouddolphinactionplugin.so
setup      : |
    %cmake_ninja -DUNIT_TESTING=false -DBUILD_SHELL_INTEGRATION_DOLPHIN=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Fix wrong file location for VFS plugin
    # https://github.com/nextcloud/desktop/issues/3781
    install -d $installdir/usr/lib64/qt5/plugins
    mv $installdir/usr/lib64/nextcloudsync_vfs_suffix.so $installdir/usr/lib64/qt5/plugins/nextcloudsync_vfs_suffix.so
    mv $installdir/usr/lib64/nextcloudsync_vfs_xattr.so $installdir/usr/lib64/qt5/plugins/nextcloudsync_vfs_xattr.so
