name       : nextcloud-client
version    : 3.0.3
release    : 22
source     :
    - https://github.com/nextcloud/desktop/archive/v3.0.3.tar.gz : abd021ff06ecb267221a221dbf8b4efd3bd8e418053cc49b6b6faa290717c6d8
license    : GPL-2.0-or-later
component  :
    - network.download
    - dolphin-integration : network.download
libsplit   : no
summary    :
    - Nextcloud client enables you to connect to your private Nextcloud Server. With it you can create directories in your home directory, and keep the contents of those directories synced with the server. Simply copy a file into the directory and the desktop synchronisation client does the rest.
    - dolphin-integration : Dolphin file manager integration for the Nextcloud client.
description:
    - Nextcloud client enables you to connect to your private Nextcloud Server. With it you can create directories in your home directory, and keep the contents of those directories synced with the server. Simply copy a file into the directory and the desktop synchronisation client does the rest.
    - dolphin-integration : Dolphin file manager integration for the Nextcloud client.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(cloudproviders)
    - pkgconfig(sqlite3)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
    - libiconv-devel
    - qtkeychain-devel
    - xdg-utils
rundeps    :
    - libgnome-keyring
    - qt5-graphicaleffects
    - qt5-svg
    - qt5-webengine
    - qt5-webkit
    - dolphin-integration :
        - nextcloud-client
patterns   :
    - dolphin-integration :
        - /usr/lib64/libnextclouddolphinpluginhelper.so
        - /usr/lib64/qt5/*
        - /usr/share/kservices5/*
setup      : |
    %cmake_ninja -DUNIT_TESTING=false -DBUILD_SHELL_INTEGRATION_DOLPHIN=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove nemo extensions
    rm -rf $installdir/usr/share/nemo-python
